basePath: /
host: localhost:8080
info:
  contact: {}
  description: A simple proxy to Pipedrive API for managing deals.
  title: Pipedrive Deals API
  version: "1.0"
paths:
  /deals:
    get:
      description: Retrieves all deals from the Pipedrive API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Retrieve all deals
    post:
      consumes:
      - application/json
      description: Creates a new deal via the Pipedrive API
      parameters:
      - description: Deal data
        in: body
        name: deal
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Create a new deal
    put:
      consumes:
      - application/json
      description: Updates an existing deal via the Pipedrive API. Expects an "id"
        field in the JSON body.
      parameters:
      - description: Deal data (must include 'id')
        in: body
        name: deal
        required: true
        schema:
          additionalProperties: true
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Update an existing deal
schemes:
- http
swagger: "2.0"
