basePath: /
definitions:
  main.CreateDeal:
    type: object
  main.UpdateDeal:
    type: object
host: localhost:8080
info:
  contact: {}
  description: A simple proxy to Pipedrive API for managing deals.
  title: Pipedrive Deals API
  version: "1.0"
paths:
  /deals:
    get:
      description: Retrieves all deals from the Pipedrive API with optional query
        parameters.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Retrieve all deals
    post:
      consumes:
      - application/json
      description: Creates a new deal via the Pipedrive API.
      parameters:
      - description: Deal data
        in: body
        name: deal
        required: true
        schema:
          $ref: '#/definitions/main.CreateDeal'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Create a new deal
  /deals/{id}:
    put:
      consumes:
      - application/json
      description: Updates an existing deal via the Pipedrive API.
      parameters:
      - description: The ID of the deal
        in: path
        name: id
        required: true
        type: integer
      - description: Deal update data
        in: body
        name: deal
        required: true
        schema:
          $ref: '#/definitions/main.UpdateDeal'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - ApiKeyAuth: []
      summary: Update an existing deal
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: query
    name: api_token
    type: apiKey
swagger: "2.0"
