name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'  # Use Go 1.24

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Run linter
        run: go vet ./...
